env:
  browser: true
  es2021: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  space-before-function-paren:
  - error
  - never
  operator-linebreak:
  - error
  - before
ignorePatterns:
  - lib/**/*
  - tests/**/*
  - jest.config.js
