name: timeparse tests

on: 
  push:
    paths:
    - '**.ts'
    - 'jest.config.js'
    - 'package-lock.json'
    - 'package.json'
    - 'tsconfig.json'
    - '.github/workflows/test.yaml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 16, 17]
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    - 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    -
      name: Installing dev dependencies
      run: npm install
    - 
      name: Running tests
      run: npm run test
